import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      style={{
        background: 'linear-gradient(90deg, #fffbe6 0%, #f5e9c6 100%)',
        fontFamily: 'Inter, Arial, sans-serif',
      }}
    >
      <body
        style={{
          background: 'linear-gradient(90deg, #fffbe6 0%, #f5e9c6 100%)',
          fontFamily: 'Inter, Arial, sans-serif',
          color: '#171717',
          minHeight: '100vh',
        }}
      >
        {children}
      </body>
    </html>
  );
}
