//
//  SavePaintingSessionTests.swift
//  GeoWCSTests – DementiaMedia Unit Tests
//
//  Copyright © 2026 World Class Scholars. All rights reserved.
//  Developed under the leadership of Dr. Christopher Appiah-Thompson
//
//  TDD unit tests for SavePaintingSession use case.
//  Covers: validation, auto-titling, persistence, and error paths.
//

import XCTest
@testable import DementiaMedia

final class SavePaintingSessionTests: XCTestCase {

    private var repository: FakeMediaRepository!
    private var fileManager: FakeFileManager!
    private var sut: SavePaintingSession!

    private let ownerID = UUID()
    private let validPNG = Data("PNG_DATA".utf8)    // non-empty placeholder

    override func setUp() {
        super.setUp()
        repository  = FakeMediaRepository()
        fileManager = FakeFileManager()
        sut = SavePaintingSession(repository: repository, fileManager: fileManager)
    }

    override func tearDown() {
        sut = nil
        super.tearDown()
    }

    // MARK: - Happy path

    func testSavingValidPaintingReturnsAssetWithCorrectKind() async throws {
        let asset = try await sut.execute(
            pngData: validPNG, title: "My Flowers", ownerID: ownerID)
        XCTAssertEqual(asset.kind, .painting)
    }

    func testSavedAssetHasCorrectOwner() async throws {
        let asset = try await sut.execute(
            pngData: validPNG, title: "Ocean", ownerID: ownerID)
        XCTAssertEqual(asset.ownerID, ownerID)
    }

    func testSavedAssetStateIsSaved() async throws {
        let asset = try await sut.execute(
            pngData: validPNG, title: "Garden", ownerID: ownerID)
        XCTAssertEqual(asset.state, .saved)
    }

    func testSavedAssetHasLocalURL() async throws {
        let asset = try await sut.execute(
            pngData: validPNG, title: "Sky", ownerID: ownerID)
        XCTAssertNotNil(asset.localURL)
    }

    func testRepositoryCalledOnce() async throws {
        _ = try await sut.execute(pngData: validPNG, title: "Portrait", ownerID: ownerID)
        XCTAssertEqual(repository.saveCallCount, 1)
    }

    func testProvidedTitleIsUsed() async throws {
        let asset = try await sut.execute(
            pngData: validPNG, title: "Autumn Leaves", ownerID: ownerID)
        XCTAssertEqual(asset.title, "Autumn Leaves")
    }

    // MARK: - Auto-title

    func testBlankTitleReceivesAutoGeneratedTitle() async throws {
        let asset = try await sut.execute(
            pngData: validPNG, title: "", ownerID: ownerID)
        XCTAssertFalse(asset.title.isEmpty)
        XCTAssertTrue(asset.title.hasPrefix("Painting "),
            "Auto-title should start with 'Painting ': '\(asset.title)'")
    }

    func testWhitespaceTitleReceivesAutoGeneratedTitle() async throws {
        let asset = try await sut.execute(
            pngData: validPNG, title: "   ", ownerID: ownerID)
        XCTAssertTrue(asset.title.hasPrefix("Painting "))
    }

    // MARK: - Validation errors

    func testEmptyPNGDataThrowsEmptyCanvasError() async {
        do {
            _ = try await sut.execute(pngData: Data(), title: "Empty", ownerID: ownerID)
            XCTFail("Expected emptyCanvas error")
        } catch let error as SavePaintingError {
            XCTAssertEqual(error, .emptyCanvas)
        }
    }

    func testTitleAtMaximumLengthSucceeds() async throws {
        let title = String(repeating: "T", count: SavePaintingSession.maximumTitleLength)
        let asset = try await sut.execute(pngData: validPNG, title: title, ownerID: ownerID)
        XCTAssertEqual(asset.title, title)
    }

    func testTitleOneCharOverLimitThrows() async {
        let title = String(repeating: "T", count: SavePaintingSession.maximumTitleLength + 1)
        do {
            _ = try await sut.execute(pngData: validPNG, title: title, ownerID: ownerID)
            XCTFail("Expected titleTooLong error")
        } catch let error as SavePaintingError {
            if case .titleTooLong(let limit) = error {
                XCTAssertEqual(limit, SavePaintingSession.maximumTitleLength)
            } else {
                XCTFail("Wrong error: \(error)")
            }
        }
    }

    // MARK: - Repository failure

    func testRepositoryFailureThrowsPersistenceError() async {
        repository.shouldFailOnSave = true
        do {
            _ = try await sut.execute(pngData: validPNG, title: "Fail", ownerID: ownerID)
            XCTFail("Expected persistenceFailure error")
        } catch let error as SavePaintingError {
            if case .persistenceFailure = error { /* expected */ } else {
                XCTFail("Wrong error: \(error)")
            }
        }
    }

    // MARK: - Tags

    func testTagsAreStoredOnAsset() async throws {
        let asset = try await sut.execute(
            pngData: validPNG, title: "Tagged", ownerID: ownerID,
            tags: ["calm", "morning"])
        XCTAssertEqual(asset.tags, ["calm", "morning"])
    }
}
